default_language_version:
    python: python3
repos:

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade

-   repo: local
    hooks:

    - id: ruff
      name: ruff
      entry: ruff
      language: python
      types: [ python ]
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
    - id: mypy
      name: mypy
      entry: mypy
      language: python
      files: restlogger/
      types: [ python ]
      args: ["--config-file=pyproject.toml", "--ignore-missing-imports"]
