# This workflow will run test with pytets inside a tox environment

name: Python Static Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      -
jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Tests with tox 
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox -e static-checks
